/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SeriesRouteImport } from './routes/series'
import { Route as LatestRouteImport } from './routes/latest'
import { Route as GenresRouteImport } from './routes/genres'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SeriesSlugRouteImport } from './routes/series.$slug'

const SeriesRoute = SeriesRouteImport.update({
  id: '/series',
  path: '/series',
  getParentRoute: () => rootRouteImport,
} as any)
const LatestRoute = LatestRouteImport.update({
  id: '/latest',
  path: '/latest',
  getParentRoute: () => rootRouteImport,
} as any)
const GenresRoute = GenresRouteImport.update({
  id: '/genres',
  path: '/genres',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SeriesSlugRoute = SeriesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SeriesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/genres': typeof GenresRoute
  '/latest': typeof LatestRoute
  '/series': typeof SeriesRouteWithChildren
  '/series/$slug': typeof SeriesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/genres': typeof GenresRoute
  '/latest': typeof LatestRoute
  '/series': typeof SeriesRouteWithChildren
  '/series/$slug': typeof SeriesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/genres': typeof GenresRoute
  '/latest': typeof LatestRoute
  '/series': typeof SeriesRouteWithChildren
  '/series/$slug': typeof SeriesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/genres' | '/latest' | '/series' | '/series/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/genres' | '/latest' | '/series' | '/series/$slug'
  id: '__root__' | '/' | '/genres' | '/latest' | '/series' | '/series/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GenresRoute: typeof GenresRoute
  LatestRoute: typeof LatestRoute
  SeriesRoute: typeof SeriesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/series': {
      id: '/series'
      path: '/series'
      fullPath: '/series'
      preLoaderRoute: typeof SeriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/latest': {
      id: '/latest'
      path: '/latest'
      fullPath: '/latest'
      preLoaderRoute: typeof LatestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/genres': {
      id: '/genres'
      path: '/genres'
      fullPath: '/genres'
      preLoaderRoute: typeof GenresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/series/$slug': {
      id: '/series/$slug'
      path: '/$slug'
      fullPath: '/series/$slug'
      preLoaderRoute: typeof SeriesSlugRouteImport
      parentRoute: typeof SeriesRoute
    }
  }
}

interface SeriesRouteChildren {
  SeriesSlugRoute: typeof SeriesSlugRoute
}

const SeriesRouteChildren: SeriesRouteChildren = {
  SeriesSlugRoute: SeriesSlugRoute,
}

const SeriesRouteWithChildren =
  SeriesRoute._addFileChildren(SeriesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GenresRoute: GenresRoute,
  LatestRoute: LatestRoute,
  SeriesRoute: SeriesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
