/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SeriesRouteImport } from './routes/series'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PremiumRouteImport } from './routes/premium'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as LatestRouteImport } from './routes/latest'
import { Route as GenresRouteImport } from './routes/genres'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DmcaRouteImport } from './routes/dmca'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SeriesSlugRouteImport } from './routes/series.$slug'
import { Route as ApiSitemapDotxmlRouteImport } from './routes/api/sitemap[.]xml'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminBotRouteImport } from './routes/admin.bot'
import { Route as AdminAiRouteImport } from './routes/admin.ai'
import { Route as SeriesSlugChapterNumberRouteImport } from './routes/series.$slug.chapter.$number'
import { Route as ApiPublicHooksPublishScheduledChaptersRouteImport } from './routes/api/public/hooks/publish-scheduled-chapters'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SeriesRoute = SeriesRouteImport.update({
  id: '/series',
  path: '/series',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumRoute = PremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const LatestRoute = LatestRouteImport.update({
  id: '/latest',
  path: '/latest',
  getParentRoute: () => rootRouteImport,
} as any)
const GenresRoute = GenresRouteImport.update({
  id: '/genres',
  path: '/genres',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DmcaRoute = DmcaRouteImport.update({
  id: '/dmca',
  path: '/dmca',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SeriesSlugRoute = SeriesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SeriesRoute,
} as any)
const ApiSitemapDotxmlRoute = ApiSitemapDotxmlRouteImport.update({
  id: '/api/sitemap.xml',
  path: '/api/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBotRoute = AdminBotRouteImport.update({
  id: '/bot',
  path: '/bot',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAiRoute = AdminAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AdminRoute,
} as any)
const SeriesSlugChapterNumberRoute = SeriesSlugChapterNumberRouteImport.update({
  id: '/chapter/$number',
  path: '/chapter/$number',
  getParentRoute: () => SeriesSlugRoute,
} as any)
const ApiPublicHooksPublishScheduledChaptersRoute =
  ApiPublicHooksPublishScheduledChaptersRouteImport.update({
    id: '/api/public/hooks/publish-scheduled-chapters',
    path: '/api/public/hooks/publish-scheduled-chapters',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/dmca': typeof DmcaRoute
  '/faq': typeof FaqRoute
  '/genres': typeof GenresRoute
  '/latest': typeof LatestRoute
  '/library': typeof LibraryRoute
  '/premium': typeof PremiumRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/series': typeof SeriesRouteWithChildren
  '/terms': typeof TermsRoute
  '/admin/ai': typeof AdminAiRoute
  '/admin/bot': typeof AdminBotRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/api/sitemap.xml': typeof ApiSitemapDotxmlRoute
  '/series/$slug': typeof SeriesSlugRouteWithChildren
  '/api/public/hooks/publish-scheduled-chapters': typeof ApiPublicHooksPublishScheduledChaptersRoute
  '/series/$slug/chapter/$number': typeof SeriesSlugChapterNumberRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/dmca': typeof DmcaRoute
  '/faq': typeof FaqRoute
  '/genres': typeof GenresRoute
  '/latest': typeof LatestRoute
  '/library': typeof LibraryRoute
  '/premium': typeof PremiumRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/series': typeof SeriesRouteWithChildren
  '/terms': typeof TermsRoute
  '/admin/ai': typeof AdminAiRoute
  '/admin/bot': typeof AdminBotRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/api/sitemap.xml': typeof ApiSitemapDotxmlRoute
  '/series/$slug': typeof SeriesSlugRouteWithChildren
  '/api/public/hooks/publish-scheduled-chapters': typeof ApiPublicHooksPublishScheduledChaptersRoute
  '/series/$slug/chapter/$number': typeof SeriesSlugChapterNumberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/dmca': typeof DmcaRoute
  '/faq': typeof FaqRoute
  '/genres': typeof GenresRoute
  '/latest': typeof LatestRoute
  '/library': typeof LibraryRoute
  '/premium': typeof PremiumRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/series': typeof SeriesRouteWithChildren
  '/terms': typeof TermsRoute
  '/admin/ai': typeof AdminAiRoute
  '/admin/bot': typeof AdminBotRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/api/sitemap.xml': typeof ApiSitemapDotxmlRoute
  '/series/$slug': typeof SeriesSlugRouteWithChildren
  '/api/public/hooks/publish-scheduled-chapters': typeof ApiPublicHooksPublishScheduledChaptersRoute
  '/series/$slug/chapter/$number': typeof SeriesSlugChapterNumberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/dmca'
    | '/faq'
    | '/genres'
    | '/latest'
    | '/library'
    | '/premium'
    | '/privacy'
    | '/profile'
    | '/series'
    | '/terms'
    | '/admin/ai'
    | '/admin/bot'
    | '/admin/settings'
    | '/api/sitemap.xml'
    | '/series/$slug'
    | '/api/public/hooks/publish-scheduled-chapters'
    | '/series/$slug/chapter/$number'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/dmca'
    | '/faq'
    | '/genres'
    | '/latest'
    | '/library'
    | '/premium'
    | '/privacy'
    | '/profile'
    | '/series'
    | '/terms'
    | '/admin/ai'
    | '/admin/bot'
    | '/admin/settings'
    | '/api/sitemap.xml'
    | '/series/$slug'
    | '/api/public/hooks/publish-scheduled-chapters'
    | '/series/$slug/chapter/$number'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/dmca'
    | '/faq'
    | '/genres'
    | '/latest'
    | '/library'
    | '/premium'
    | '/privacy'
    | '/profile'
    | '/series'
    | '/terms'
    | '/admin/ai'
    | '/admin/bot'
    | '/admin/settings'
    | '/api/sitemap.xml'
    | '/series/$slug'
    | '/api/public/hooks/publish-scheduled-chapters'
    | '/series/$slug/chapter/$number'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  DmcaRoute: typeof DmcaRoute
  FaqRoute: typeof FaqRoute
  GenresRoute: typeof GenresRoute
  LatestRoute: typeof LatestRoute
  LibraryRoute: typeof LibraryRoute
  PremiumRoute: typeof PremiumRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  SeriesRoute: typeof SeriesRouteWithChildren
  TermsRoute: typeof TermsRoute
  ApiSitemapDotxmlRoute: typeof ApiSitemapDotxmlRoute
  ApiPublicHooksPublishScheduledChaptersRoute: typeof ApiPublicHooksPublishScheduledChaptersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/series': {
      id: '/series'
      path: '/series'
      fullPath: '/series'
      preLoaderRoute: typeof SeriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium': {
      id: '/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof PremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/latest': {
      id: '/latest'
      path: '/latest'
      fullPath: '/latest'
      preLoaderRoute: typeof LatestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/genres': {
      id: '/genres'
      path: '/genres'
      fullPath: '/genres'
      preLoaderRoute: typeof GenresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dmca': {
      id: '/dmca'
      path: '/dmca'
      fullPath: '/dmca'
      preLoaderRoute: typeof DmcaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/series/$slug': {
      id: '/series/$slug'
      path: '/$slug'
      fullPath: '/series/$slug'
      preLoaderRoute: typeof SeriesSlugRouteImport
      parentRoute: typeof SeriesRoute
    }
    '/api/sitemap.xml': {
      id: '/api/sitemap.xml'
      path: '/api/sitemap.xml'
      fullPath: '/api/sitemap.xml'
      preLoaderRoute: typeof ApiSitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bot': {
      id: '/admin/bot'
      path: '/bot'
      fullPath: '/admin/bot'
      preLoaderRoute: typeof AdminBotRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ai': {
      id: '/admin/ai'
      path: '/ai'
      fullPath: '/admin/ai'
      preLoaderRoute: typeof AdminAiRouteImport
      parentRoute: typeof AdminRoute
    }
    '/series/$slug/chapter/$number': {
      id: '/series/$slug/chapter/$number'
      path: '/chapter/$number'
      fullPath: '/series/$slug/chapter/$number'
      preLoaderRoute: typeof SeriesSlugChapterNumberRouteImport
      parentRoute: typeof SeriesSlugRoute
    }
    '/api/public/hooks/publish-scheduled-chapters': {
      id: '/api/public/hooks/publish-scheduled-chapters'
      path: '/api/public/hooks/publish-scheduled-chapters'
      fullPath: '/api/public/hooks/publish-scheduled-chapters'
      preLoaderRoute: typeof ApiPublicHooksPublishScheduledChaptersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAiRoute: typeof AdminAiRoute
  AdminBotRoute: typeof AdminBotRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAiRoute: AdminAiRoute,
  AdminBotRoute: AdminBotRoute,
  AdminSettingsRoute: AdminSettingsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface SeriesSlugRouteChildren {
  SeriesSlugChapterNumberRoute: typeof SeriesSlugChapterNumberRoute
}

const SeriesSlugRouteChildren: SeriesSlugRouteChildren = {
  SeriesSlugChapterNumberRoute: SeriesSlugChapterNumberRoute,
}

const SeriesSlugRouteWithChildren = SeriesSlugRoute._addFileChildren(
  SeriesSlugRouteChildren,
)

interface SeriesRouteChildren {
  SeriesSlugRoute: typeof SeriesSlugRouteWithChildren
}

const SeriesRouteChildren: SeriesRouteChildren = {
  SeriesSlugRoute: SeriesSlugRouteWithChildren,
}

const SeriesRouteWithChildren =
  SeriesRoute._addFileChildren(SeriesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  DmcaRoute: DmcaRoute,
  FaqRoute: FaqRoute,
  GenresRoute: GenresRoute,
  LatestRoute: LatestRoute,
  LibraryRoute: LibraryRoute,
  PremiumRoute: PremiumRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  SeriesRoute: SeriesRouteWithChildren,
  TermsRoute: TermsRoute,
  ApiSitemapDotxmlRoute: ApiSitemapDotxmlRoute,
  ApiPublicHooksPublishScheduledChaptersRoute:
    ApiPublicHooksPublishScheduledChaptersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
