/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SeriesRouteImport } from './routes/series'
import { Route as PremiumRouteImport } from './routes/premium'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as LatestRouteImport } from './routes/latest'
import { Route as GenresRouteImport } from './routes/genres'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SeriesSlugRouteImport } from './routes/series.$slug'
import { Route as SeriesSlugChapterNumberRouteImport } from './routes/series.$slug.chapter.$number'

const SeriesRoute = SeriesRouteImport.update({
  id: '/series',
  path: '/series',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumRoute = PremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const LatestRoute = LatestRouteImport.update({
  id: '/latest',
  path: '/latest',
  getParentRoute: () => rootRouteImport,
} as any)
const GenresRoute = GenresRouteImport.update({
  id: '/genres',
  path: '/genres',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SeriesSlugRoute = SeriesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SeriesRoute,
} as any)
const SeriesSlugChapterNumberRoute = SeriesSlugChapterNumberRouteImport.update({
  id: '/chapter/$number',
  path: '/chapter/$number',
  getParentRoute: () => SeriesSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/genres': typeof GenresRoute
  '/latest': typeof LatestRoute
  '/library': typeof LibraryRoute
  '/premium': typeof PremiumRoute
  '/series': typeof SeriesRouteWithChildren
  '/series/$slug': typeof SeriesSlugRouteWithChildren
  '/series/$slug/chapter/$number': typeof SeriesSlugChapterNumberRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/genres': typeof GenresRoute
  '/latest': typeof LatestRoute
  '/library': typeof LibraryRoute
  '/premium': typeof PremiumRoute
  '/series': typeof SeriesRouteWithChildren
  '/series/$slug': typeof SeriesSlugRouteWithChildren
  '/series/$slug/chapter/$number': typeof SeriesSlugChapterNumberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/genres': typeof GenresRoute
  '/latest': typeof LatestRoute
  '/library': typeof LibraryRoute
  '/premium': typeof PremiumRoute
  '/series': typeof SeriesRouteWithChildren
  '/series/$slug': typeof SeriesSlugRouteWithChildren
  '/series/$slug/chapter/$number': typeof SeriesSlugChapterNumberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/genres'
    | '/latest'
    | '/library'
    | '/premium'
    | '/series'
    | '/series/$slug'
    | '/series/$slug/chapter/$number'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/genres'
    | '/latest'
    | '/library'
    | '/premium'
    | '/series'
    | '/series/$slug'
    | '/series/$slug/chapter/$number'
  id:
    | '__root__'
    | '/'
    | '/genres'
    | '/latest'
    | '/library'
    | '/premium'
    | '/series'
    | '/series/$slug'
    | '/series/$slug/chapter/$number'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GenresRoute: typeof GenresRoute
  LatestRoute: typeof LatestRoute
  LibraryRoute: typeof LibraryRoute
  PremiumRoute: typeof PremiumRoute
  SeriesRoute: typeof SeriesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/series': {
      id: '/series'
      path: '/series'
      fullPath: '/series'
      preLoaderRoute: typeof SeriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium': {
      id: '/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof PremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/latest': {
      id: '/latest'
      path: '/latest'
      fullPath: '/latest'
      preLoaderRoute: typeof LatestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/genres': {
      id: '/genres'
      path: '/genres'
      fullPath: '/genres'
      preLoaderRoute: typeof GenresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/series/$slug': {
      id: '/series/$slug'
      path: '/$slug'
      fullPath: '/series/$slug'
      preLoaderRoute: typeof SeriesSlugRouteImport
      parentRoute: typeof SeriesRoute
    }
    '/series/$slug/chapter/$number': {
      id: '/series/$slug/chapter/$number'
      path: '/chapter/$number'
      fullPath: '/series/$slug/chapter/$number'
      preLoaderRoute: typeof SeriesSlugChapterNumberRouteImport
      parentRoute: typeof SeriesSlugRoute
    }
  }
}

interface SeriesSlugRouteChildren {
  SeriesSlugChapterNumberRoute: typeof SeriesSlugChapterNumberRoute
}

const SeriesSlugRouteChildren: SeriesSlugRouteChildren = {
  SeriesSlugChapterNumberRoute: SeriesSlugChapterNumberRoute,
}

const SeriesSlugRouteWithChildren = SeriesSlugRoute._addFileChildren(
  SeriesSlugRouteChildren,
)

interface SeriesRouteChildren {
  SeriesSlugRoute: typeof SeriesSlugRouteWithChildren
}

const SeriesRouteChildren: SeriesRouteChildren = {
  SeriesSlugRoute: SeriesSlugRouteWithChildren,
}

const SeriesRouteWithChildren =
  SeriesRoute._addFileChildren(SeriesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GenresRoute: GenresRoute,
  LatestRoute: LatestRoute,
  LibraryRoute: LibraryRoute,
  PremiumRoute: PremiumRoute,
  SeriesRoute: SeriesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
